### ISSUE TITLE
In custom buckets configuration, string having dot is not working

### ISSUE THREAD

**Issue by ashokwaghmare** [kamon-io/kamon-prometheus#16]
Not working - 
custom {
      "akka.actor.processing-time" = [0.1, 1.0, 10.0]
 }
------------------------------------------------------------------------
Though, string without dot works, below conf works fine.
custom {
      "plain_string" = [0.1, 1.0, 10.0]
}

Probable fix would be, in PrometheusReporter.scala --> def readCustomBuckets,   

"k" - variable needs to be in double quotes while passing to, getDoubleList(k), 

I might be wrong.

Thanks

**Comment by ivantopo** [comment]
Interesting, let me take a look at that.

**Comment by ivantopo** [comment]
Thanks for reporting, @ashokwaghmare.

Fixed in [v1.1.1](https://github.com/kamon-io/kamon-prometheus/releases/tag/v1.1.1). Available on Bintray and on its way to Central.

**Comment by ashokwaghmare** [comment]
Great, Thanks for your help, @ivantopo
