### ISSUE TITLE
Question: how to scrape the prometheus reporter in v2.0.0?

### ISSUE THREAD

**Issue by dcastro** [kamon-io/kamon-prometheus#35]
To manually scrape the reporter in v1, you can do something like this:

```scala
val reporter = new PrometheusReporter()
Kamon.addReporter(new PrometheusReporter())

val data = reporter.scrapeData()
```

But in v2, `Kamon.addReporter` doesn't exist anymore. What's the correct way of doing this in v2?

**Comment by jneumaier** [comment]
I used the following workaround in Java to register my own PrometheusReporter instance (serving the scrape data on another HTTP server with TLS support):

```java
Kamon.init(config);
Kamon._moduleRegistry().register("Prometheus Reporter", scala.Option.apply(null), prometheusReporter);
```

If this does not work a reporter with the exact same name "Prometheus Reporter" might have already been registered. In this case the ModuleRegistry might skip registration with a warning ("Cannot register module [$name], a module with that name already exists.")

**Comment by ane** [comment]
You can probably get away with by disabling the built-in module by setting `kamon.modules.prometheus-reporter.enabled` to `false` and then starting the reporter manually:

```scala
val reporter = new PrometheusReporter
Kamon.registerModule("prometheus", reporter)
// ...
val data = reporter.scrapeData()
```

**Comment by dcastro** [comment]
Thanks @ane! Replacing `addReporter` with `registerModule` worked!
